[project]
name = "finance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "hydra-core>=1.3.2",
    "mcp[cli]>=1.2.0",
    "pydantic>=2.11.7",
    "pytest>=9.0.3",
    "t-tech-investments>=0.3.5",
    "uvicorn>=0.35.0",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
finance_cli = "finance_agent.client.cli:main"
finance_eval = "finance_agent.evals.cli:main"
mcp_server = "finance_agent.harness.mcp_server:main"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]
fixable = ["I", "E", "W"]
ignore = [
    "B904",  # Поднятие ошибок в except
    "B008",  # Depends
    "E712",  # Использование == False
]

[tool.pytest.ini_options]
pythonpath = [".", "src"]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
]

[[tool.uv.index]]
name = "tbank"
url = "https://opensource.tbank.ru/api/v4/projects/238/packages/pypi/simple"
explicit = true

[tool.uv.sources]
t-tech-investments = { index = "tbank" }
